language: php
php:
  - 7.2
cache:
  directories:
    - vendor
install:
  - mkdir -p ~/bin/ && export export PATH="~/bin/:$PATH"
  - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ~/bin
  - composer install
script:
  - ./vendor/bin/phpstan --error-format=raw --level=max analyse | reviewdog -f=phpstan -reporter=github-pr-review
